#include <iostream>
#include "DataStructuresLab10Task3.h" // Includes proper header file (graph that holds strings instead of integers)

using namespace std;

int main() {
	Graph graph1; // Defines graph
	graph1.addVertex("Alabama"); // Begins adding all 50 states in alphabetical order to the graph
	graph1.addVertex("Alaska");
	graph1.addVertex("Arizona");
	graph1.addVertex("Arkansas");
	graph1.addVertex("California");
	graph1.addVertex("Colorado");
	graph1.addVertex("Connecticut");
	graph1.addVertex("Delaware");
	graph1.addVertex("Florida");
	graph1.addVertex("Georgia");
	graph1.addVertex("Hawaii");
	graph1.addVertex("Idaho");
	graph1.addVertex("Illinois");
	graph1.addVertex("Indiana");
	graph1.addVertex("Iowa");
	graph1.addVertex("Kansas");
	graph1.addVertex("Kentucky");
	graph1.addVertex("Louisiana");
	graph1.addVertex("Maine");
	graph1.addVertex("Maryland");
	graph1.addVertex("Massachusetts");
	graph1.addVertex("Michigan");
	graph1.addVertex("Minnesota");
	graph1.addVertex("Mississippi");
	graph1.addVertex("Missouri");
	graph1.addVertex("Montana");
	graph1.addVertex("Nebraska");
	graph1.addVertex("Nevada");
	graph1.addVertex("New Hampshire");
	graph1.addVertex("New Jersey");
	graph1.addVertex("New Mexico");
	graph1.addVertex("New York");
	graph1.addVertex("North Carolina");
	graph1.addVertex("North Dakota");
	graph1.addVertex("Ohio");
	graph1.addVertex("Oklahoma");
	graph1.addVertex("Oregon");
	graph1.addVertex("Pennsylvania");
	graph1.addVertex("Rhode Island");
	graph1.addVertex("South Carolina");
	graph1.addVertex("South Dakota");
	graph1.addVertex("Tennessee");
	graph1.addVertex("Texas");
	graph1.addVertex("Utah");
	graph1.addVertex("Vermont");
	graph1.addVertex("Virginia");
	graph1.addVertex("Washington");
	graph1.addVertex("West Virginia");
	graph1.addVertex("Wisconsin");
	graph1.addVertex("Wyoming");
	graph1.addEdge("Alabama", "Florida"); // Begins adding edges for all states that each state borders
	graph1.addEdge("Alabama", "Georgia");
	graph1.addEdge("Alabama", "Tennessee");
	graph1.addEdge("Alabama", "Mississippi");
	graph1.addEdge("Arizona", "California");
	graph1.addEdge("Arizona", "Nevada");
	graph1.addEdge("Arizona", "Utah");
	graph1.addEdge("Arizona", "New Mexico");
	graph1.addEdge("Arkansas", "Texas");
	graph1.addEdge("Arkansas", "Oklahoma");
	graph1.addEdge("Arkansas", "Missouri");
	graph1.addEdge("Arkansas", "Tennessee");
	graph1.addEdge("Arkansas", "Mississippi");
	graph1.addEdge("Arkansas", "Louisiana");
	graph1.addEdge("California", "Oregon");
	graph1.addEdge("California", "Nevada");
	graph1.addEdge("California", "Arizona");
	graph1.addEdge("Colorado", "Utah");
	graph1.addEdge("Colorado", "Wyoming");
	graph1.addEdge("Colorado", "Nebraska");
	graph1.addEdge("Colorado", "Kansas");
	graph1.addEdge("Colorado", "Oklahoma");
	graph1.addEdge("Colorado", "New Mexico");
	graph1.addEdge("Connecticut", "Rhode Island");
	graph1.addEdge("Connecticut", "Massachusetts");
	graph1.addEdge("Connecticut", "New York");
	graph1.addEdge("Delaware", "Maryland");
	graph1.addEdge("Delaware", "Pennsylvania");
	graph1.addEdge("Delaware", "New Jersey");
	graph1.addEdge("Florida", "Georgia");
	graph1.addEdge("Florida", "Alabama");
	graph1.addEdge("Georgia", "Florida");
	graph1.addEdge("Georgia", "Alabama");
	graph1.addEdge("Georgia", "Tennessee");
	graph1.addEdge("Georgia", "North Carolina");
	graph1.addEdge("Georgia", "South Carolina");
	graph1.addEdge("Idaho", "Washington");
	graph1.addEdge("Idaho", "Oregon");
	graph1.addEdge("Idaho", "Nevada");
	graph1.addEdge("Idaho", "Utah");
	graph1.addEdge("Idaho", "Wyoming");
	graph1.addEdge("Idaho", "Montana");
	graph1.addEdge("Illinois", "Wisconsin");
	graph1.addEdge("Illinois", "Iowa");
	graph1.addEdge("Illinois", "Missouri");
	graph1.addEdge("Illinois", "Kentucky");
	graph1.addEdge("Illinois", "Indiana");
	graph1.addEdge("Indiana", "Ohio");
	graph1.addEdge("Indiana", "Michigan");
	graph1.addEdge("Indiana", "Illinois");
	graph1.addEdge("Indiana", "Kentucky");
	graph1.addEdge("Iowa", "Minnesota");
	graph1.addEdge("Iowa", "Wisconsin");
	graph1.addEdge("Iowa", "Illinois");
	graph1.addEdge("Iowa", "Missouri");
	graph1.addEdge("Iowa", "Nebraska");
	graph1.addEdge("Iowa", "South Dakota");
	graph1.addEdge("Kansas", "Nebraska");
	graph1.addEdge("Kansas", "Missouri");
	graph1.addEdge("Kansas", "Oklahoma");
	graph1.addEdge("Kansas", "Colorado");
	graph1.addEdge("Kentucky", "Ohio");
	graph1.addEdge("Kentucky", "West Virginia");
	graph1.addEdge("Kentucky", "Virginia");
	graph1.addEdge("Kentucky", "Tennessee");
	graph1.addEdge("Kentucky", "Missouri");
	graph1.addEdge("Kentucky", "Illinois");
	graph1.addEdge("Kentucky", "Indiana");
	graph1.addEdge("Louisiana", "Mississippi");
	graph1.addEdge("Louisiana", "Arkansas");
	graph1.addEdge("Louisiana", "Texas");
	graph1.addEdge("Maine", "New Hampshire");
	graph1.addEdge("Maryland", "Delaware");
	graph1.addEdge("Maryland", "Pennsylvania");
	graph1.addEdge("Maryland", "West Virginia");
	graph1.addEdge("Maryland", "Virginia");
	graph1.addEdge("Massachusetts", "Rhode Island");
	graph1.addEdge("Massachusetts", "Connecticut");
	graph1.addEdge("Massachusetts", "New York");
	graph1.addEdge("Massachusetts", "Vermont");
	graph1.addEdge("Massachusetts", "New Hampshire");
	graph1.addEdge("Michigan", "Ohio");
	graph1.addEdge("Michigan", "Indiana");
	graph1.addEdge("Michigan", "Wisconsin");
	graph1.addEdge("Minnesota", "Wisconsin");
	graph1.addEdge("Minnesota", "Iowa");
	graph1.addEdge("Minnesota", "South Dakota");
	graph1.addEdge("Minnesota", "North Dakota");
	graph1.addEdge("Mississippi", "Alabama");
	graph1.addEdge("Mississippi", "Tennessee");
	graph1.addEdge("Mississippi", "Arkansas");
	graph1.addEdge("Mississippi", "Louisiana");
	graph1.addEdge("Missouri", "Iowa");
	graph1.addEdge("Missouri", "Illinois");
	graph1.addEdge("Missouri", "Kentucky");
	graph1.addEdge("Missouri", "Tennessee");
	graph1.addEdge("Missouri", "Arkansas");
	graph1.addEdge("Missouri", "Oklahoma");
	graph1.addEdge("Missouri", "Kansas");
	graph1.addEdge("Missouri", "Nebraska");
	graph1.addEdge("Montana", "Idaho");
	graph1.addEdge("Montana", "Wyoming");
	graph1.addEdge("Montana", "South Dakota");
	graph1.addEdge("Montana", "North Dakota");
	graph1.addEdge("Nebraska", "South Dakota");
	graph1.addEdge("Nebraska", "Iowa");
	graph1.addEdge("Nebraska", "Missouri");
	graph1.addEdge("Nebraska", "Kansas");
	graph1.addEdge("Nebraska", "Colorado");
	graph1.addEdge("Nebraska", "Wyoming");
	graph1.addEdge("Nevada", "Oregon");
	graph1.addEdge("Nevada", "California");
	graph1.addEdge("Nevada", "Arizona");
	graph1.addEdge("Nevada", "Utah");
	graph1.addEdge("Nevada", "Idaho");
	graph1.addEdge("New Hampshire", "Maine");
	graph1.addEdge("New Hampshire", "Vermont");
	graph1.addEdge("New Hampshire", "Massachusetts");
	graph1.addEdge("New Jersey", "New York");
	graph1.addEdge("New Jersey", "Pennsylvania");
	graph1.addEdge("New Jersey", "Delaware");
	graph1.addEdge("New Mexico", "Texas");
	graph1.addEdge("New Mexico", "Oklahoma");
	graph1.addEdge("New Mexico", "Colorado");
	graph1.addEdge("New Mexico", "Arizona");
	graph1.addEdge("New York", "Vermont");
	graph1.addEdge("New York", "Massachusetts");
	graph1.addEdge("New York", "Connecticut");
	graph1.addEdge("New York", "New Jersey");
	graph1.addEdge("New York", "Pennsylvania");
	graph1.addEdge("North Carolina", "Virginia");
	graph1.addEdge("North Carolina", "Tennessee");
	graph1.addEdge("North Carolina", "Georgia");
	graph1.addEdge("North Carolina", "South Carolina");
	graph1.addEdge("North Dakota", "Minnesota");
	graph1.addEdge("North Dakota", "South Dakota");
	graph1.addEdge("North Dakota", "Montana");
	graph1.addEdge("Ohio", "Michigan");
	graph1.addEdge("Ohio", "Pennsylvania");
	graph1.addEdge("Ohio", "West Virginia");
	graph1.addEdge("Ohio", "Kentucky");
	graph1.addEdge("Ohio", "Indiana");
	graph1.addEdge("Oklahoma", "Texas");
	graph1.addEdge("Oklahoma", "New Mexico");
	graph1.addEdge("Oklahoma", "Colorado");
	graph1.addEdge("Oklahoma", "Kansas");
	graph1.addEdge("Oklahoma", "Arkansas");
	graph1.addEdge("Oklahoma", "Missouri");
	graph1.addEdge("Oregon", "Washington");
	graph1.addEdge("Oregon", "Idaho");
	graph1.addEdge("Oregon", "Nevada");
	graph1.addEdge("Oregon", "California");
	graph1.addEdge("Pennsylvania", "New York");
	graph1.addEdge("Pennsylvania", "New Jersey");
	graph1.addEdge("Pennsylvania", "Delaware");
	graph1.addEdge("Pennsylvania", "Maryland");
	graph1.addEdge("Pennsylvania", "West Virginia");
	graph1.addEdge("Pennsylvania", "Ohio");
	graph1.addEdge("Rhode Island", "Massachusetts");
	graph1.addEdge("Rhode Island", "Connecticut");
	graph1.addEdge("South Carolina", "North Carolina");
	graph1.addEdge("South Carolina", "Georgia");
	graph1.addEdge("South Dakota", "North Dakota");
	graph1.addEdge("South Dakota", "Minnesota");
	graph1.addEdge("South Dakota", "Iowa");
	graph1.addEdge("South Dakota", "Nebraska");
	graph1.addEdge("South Dakota", "Wyoming");
	graph1.addEdge("South Dakota", "Montana");
	graph1.addEdge("Tennessee", "Kentucky");
	graph1.addEdge("Tennessee", "Virginia");
	graph1.addEdge("Tennessee", "North Carolina");
	graph1.addEdge("Tennessee", "Georgia");
	graph1.addEdge("Tennessee", "Alabama");
	graph1.addEdge("Tennessee", "Mississippi");
	graph1.addEdge("Tennessee", "Arkansas");
	graph1.addEdge("Tennessee", "Missouri");
	graph1.addEdge("Texas", "Louisiana");
	graph1.addEdge("Texas", "Arkansas");
	graph1.addEdge("Texas", "Oklahoma");
	graph1.addEdge("Texas", "New Mexico");
	graph1.addEdge("Utah", "Idaho");
	graph1.addEdge("Utah", "Wyoming");
	graph1.addEdge("Utah", "Colorado");
	graph1.addEdge("Utah", "Arizona");
	graph1.addEdge("Utah", "Nevada");
	graph1.addEdge("Vermont", "New Hampshire");
	graph1.addEdge("Vermont", "Massachusetts");
	graph1.addEdge("Vermont", "New York");
	graph1.addEdge("Virginia", "Maryland");
	graph1.addEdge("Virginia", "West Virginia");
	graph1.addEdge("Virginia", "Kentucky");
	graph1.addEdge("Virginia", "Tennessee");
	graph1.addEdge("Virginia", "North Carolina");
	graph1.addEdge("Washington", "Oregon");
	graph1.addEdge("Washington", "Idaho");
	graph1.addEdge("West Virginia", "Ohio");
	graph1.addEdge("West Virginia", "Pennsylvania");
	graph1.addEdge("West Virginia", "Maryland");
	graph1.addEdge("West Virginia", "Virginia");
	graph1.addEdge("West Virginia", "Kentucky");
	graph1.addEdge("Wisconsin", "Michigan");
	graph1.addEdge("Wisconsin", "Illinois");
	graph1.addEdge("Wisconsin", "Iowa");
	graph1.addEdge("Wisconsin", "Minnesota");
	graph1.addEdge("Wyoming", "Montana");
	graph1.addEdge("Wyoming", "Idaho");
	graph1.addEdge("Wyoming", "Utah");
	graph1.addEdge("Wyoming", "Colorado");
	graph1.addEdge("Wyoming", "Nebraska");
	graph1.addEdge("Wyoming", "South Dakota");
	graph1.PrintGraph(); // Prints graph to display each states with its bordering states
	return 0;
}